
interface DataTypes {
    id: string,
    imageUrl: string,
    siteName: string,
    shortDescription: string,
    fullDescription: string,
    btn: string,
    location: string
    origin: string,
    Region: string,
    Species: string,
    Variety: string,
    Altitude: string,       
    Process: string,
    Packaging: string,
    Harvest_period: string,
    Type_of_harvest: string,
    Drying: string
}

const OurSite = <DataTypes[]>[
    {
        id: "0",
        imageUrl: "/images/tadepic10.jpg",
        siteName: "Mendoyu",
        shortDescription: "This site located about 2400 altitude at one of the tropical regions in oromia region.",
        fullDescription: "Set in the stunning hills of Nensebo, West Arsi at 2,200 meters elevation, Mendoyu is a site where nature shapes every cup. We specialize in natural sun-dried coffee, allowing cherries to dry slowly on raised beds under the Ethiopian sun. At Mendoyu Each cherry is carefully handpicked, sorted, and sun-dried for several weeks to bring out layers of berry. Our site rests on the borderlands of Sidama and West Arsi, giving Mendoyu a unique terroir that bridges two legendary coffee zones. Mendoyu is a celebration of Ethiopia’s natural beauty and the power of sun-dried tradition. Every bean carries the warmth of our sun and the soul of our highlands.",
        btn: "Read More",
        location: "Ethiopia / Nensebo",
        origin: "Ethiopia",
        Region: "Oromia / West Arsi",
        Species: "Arabica",
        Variety: "Heirloom",
        Altitude: "2200m",       
        Process: "Sun dried station",
        Packaging: "60kg - jute bags",
        Harvest_period: "Nov - January",
        Type_of_harvest: "Manual",
        Drying: "Drying bed"
    },
    {
        id: "1",
        imageUrl: "/images/tadepic1.jpg",
        siteName: "Yemasera",
        shortDescription: "This site one of our largest site with the size of over 100 workers.",
        fullDescription: "Nestled in the highlands of West Arsi at 2,100 meters above sea level, Yemasira is a site where altitude meets excellence. this site produces highquality washed coffees that are clean, vibrant, and full of character. The farm is home to heirloom Ethiopian varieties, cultivated using traditional, sustainable methods passed down through generations. The farm is home to heirloom Ethiopian varieties, cultivated using traditional, sustainable methods passed down through generations. Our commitment to organic farming means no synthetic chemicals—just nature, soil, and careful hands.Yemasira benefits from rich soil,cool temperatures, and ample rainfall, perfect for slow cherry development and complex flavors. We carefully handpick only the ripest cherries and process them using clean water and traditional washed methods. The result is a cup with bright citrus notes and a silky body that reflects its high-altitude origins.Yemasira is more than site it’s a vision of quality, sustainability, and respect for the land. Taste the story of Ethiopia in every cup from Yemasira.",
        btn: "Read More",
        location: "Ethiopia / Nensebo",
        origin: "Ethiopia",
        Region: "Oromia / West Arsi",
        Species: "Arabica",
        Variety: "Heirloom",
        Altitude: "2100m",       
        Process: "Washing station",
        Packaging: "60kg - jute bags",
        Harvest_period: "Nov - January",
        Type_of_harvest: "Manual",
        Drying: "Drying bed"
    },
    {
        id: "2",
        imageUrl: "/images/tade-7.jpg",
        siteName: "Refisa ",
        shortDescription: "This site planted at the remote area of oromia region with abundant coffee resources.",
        fullDescription: "High in the mountains of West Arsi at an altitude of 2,200 meters, the Refisa coffee site is a gem of Ethiopian coffee excellence. Situated in the fertile lands of Nenesbo, this site thrives under ideal conditions for producing bright, high-quality washed coffees. Our high elevation slows down cherry ripening, allowing to develop deeply and flavors to become layered and complex. We focus on handpicking only the ripest cherries to ensure consistency and quality. Using the washed processing method, we highlight clarity in the cup, delivering a clean profile with vibrant acidity and floral notes. The local microclimate, cool air, and rich soil all contribute to a beautifully balanced and aromatic coffee. Refisa is rooted in a commitment to excellence and the preservation of Ethiopia’s rich coffee heritage. While we embrace innovation, our practices remain true to the wisdom of the land and its people. Each bean carries the soul of Nenesbo—honest, powerful, and full of life. Refisa isn’t just a name; it’s a statement of refusing to compromise on quality, tradition, or sustainability.",
        btn: "Read More",
        location: "Ethiopia / Nensebo",
        origin: "Ethiopia",
        Region: "Oromia / West Arsi",
        Species: "Arabica",
        Variety: "Heirloom",
        Altitude: "2200m",       
        Process: "Washing station",
        Packaging: "60kg - jute bags",
        Harvest_period: "Nov - January",
        Type_of_harvest: "Manual",
        Drying: "Drying bed"
    },
    {
        id: "3",
        imageUrl: "/images/tadepic9.jpg",
        siteName: "Mewa",
        shortDescription: "This site dedicated to improve the quality of our coffee.",
        fullDescription: "At an astonishing 2,500 meters above sea level, Mewa is one of the highest coffee-growing sites , producing truly exceptional beans. Nestled in the heart of Nensebo, West Arsi, this site benefits from cool mountain air, rich soil, and abundant natural shade. Our coffee undergoes the natural sun-dried process, where cherries are carefully handpicked and dried on raised beds until they get proper temperature  Thanks to the extreme altitude, cherries develop slowly, resulting in complex flavors, bright acidity, and remarkable depth. Nensebo Woreda is home to thousands of smallholder coffee farmers who together grow coffee on about 4500-5,000 hectares of land. On average, each farmer in Nensebo owns around two hectares of farmland. These farmers grow a wide variety of heirloom coffee plants, including some wild coffee types that naturally grow in the nearby forests.",
        btn: "Read More",
        location: "Ethiopia / Nensebo",
        origin: "Ethiopia",
        Region: "Oromia / West Arsi",
        Species: "Arabica",
        Variety: "Heirloom",
        Altitude: "2500m",       
        Process: "Sun dried station",
        Packaging: "60kg - jute bags",
        Harvest_period: "Nov - January",
        Type_of_harvest: "Manual",
        Drying: "Drying bed"
    },
    {
        id: "4",
        imageUrl: "/images/onsite-1.jpg",
        siteName: "Bulga",
        fullDescription: "Located at 2,100 meters above sea level in Bulga Kebele, Nensebo Woreda, this site produces vibrant, high-elevation coffees with bold character. Bulga is known for its rich soil, cool climate, and ideal conditions for slow cherry maturation, which enhances sweetness and density. We work with local farmers cultivating heirloom varieties, some of which trace their origins to wild forest genetics unique to Ethiopia. Our specialty is the anaerobic fermentation process, where cherries are fermented in oxygen-free tanks to unlock exotic, best flavors. Bulga is part of our Sidama Nensebo network, representing a new wave of innovation in traditional coffee regions. From farm to fermentation tank, Bulga Anaerobic is a bold expression of flavor, craft, and altitude.",
        btn: "Read More",
        location: "Ethiopia / Nensebo",
        origin: "Ethiopia",
        Region: "Oromia / West Arsi",
        Species: "Arabica",
        Variety: "Heirloom",
        Altitude: "2100",       
        Process: "Anarobic station",
        Packaging: "60kg - jute bags",
        Harvest_period: "Nov - January",
        Type_of_harvest: "Manual",
        Drying: "Drying bed"
    },
    {
        id: "5",
        imageUrl: "/images/tadepic8.jpg",
        siteName: "Shaka",
        fullDescription: "Located in the Shaka area of Nensebo, at Tulu Gola Kebele, this coffee site sits at an impressive altitude of 2,150 meters above sea level. Smallholder farmers from the surrounding communities bring their freshly harvested cherries to our processing station. Here, we use the natural (sun-dried) method, where cherries are carefully spread on raised beds and dried slowly under the sun for several days. Throughout the drying process, our team hand-sorts the cherries daily, removing any damaged or defective ones to maintain the highest quality. Until recently, coffees from this region were sold under the broader Sidama label, but we’ve worked to showcase the distinctiveness of Shaka’s terroir. The area’s high elevation, traditional practices, and unique microclimate create a flavor profile that truly stands apart. Shaka coffee is now gaining recognition for its vibrant fruit notes, clean cup, and natural sweetness. This site was strategically established in a remote part of Shaka to support and process coffees from surrounding kebeles like Belo and Aro.",
        btn: "Read More",
        location: "Ethiopia / Nensebo",
        origin: "Ethiopia",
        Region: "Oromia / West Arsi",
        Species: "Arabica",
        Variety: "Heirloom",
        Altitude: "2150",       
        Process: "Sun dried station",
        Packaging: "60kg - jute bags",
        Harvest_period: "Nov - January",
        Type_of_harvest: "Manual",
        Drying: "Drying bed"
    },
    {
        id: "6",
        imageUrl: "/images/site4.jpg",
        siteName: "Shaka",
        fullDescription: "Perched at 2,100 meters in the highlands of Tulu Gola Kebele, Nensebo Woreda, the Shaka coffee site is where innovation meets tradition. We grow diverse Ethiopian heirloom varieties, carefully selected for their complexity and adaptability to high elevation. At Shaka, we specialize in the anaerobic fermentation process—a controlled, oxygen-free environment that enhances bold, layered flavors. Farmers handpick only the ripest cherries, ensuring the highest level of quality and traceability. This site reflects the forward-thinking approach of Sidama Nensebo, blending science with Ethiopia’s legendary coffee heritage..",
        btn: "Read More",
        location: "Ethiopia / Nensebo",
        origin: "Ethiopia",
        Region: "Oromia / West Arsi",
        Species: "Arabica",
        Variety: "Heirloom",
        Altitude: "2100",       
        Process: "Anarobic station",
        Packaging: "60kg - jute bags",
        Harvest_period: "Nov - January",
        Type_of_harvest: "Manual",
        Drying: "Drying bed"
    },
    {
        id: "7",
        imageUrl: "/images/coffeeSite.JPG",
        siteName: "Mewa",
        fullDescription: "At a staggering 2,500 meters above sea level, Mewa stands as one of the highest coffee-producing sites in Ethiopia. Located in Mewa Kebele, We cultivate diverse Ethiopian heirloom varieties, carefully adapted to the extreme altitude and unique microclimate. Our standout offering is the anaerobic process, where cherries are sealed in airtight tanks for controlled fermentation. Every step—from selective handpicking to careful fermentation—is done with precision to maintain top quality. Mewa Anaerobic coffees are limited, traceable, and crafted for roasters seeking something extraordinary. Mewa is a true highland gem—elevated in both altitude and excellence.",
        btn: "Read More",
        location: "Ethiopia / Nensebo",
        origin: "Ethiopia",
        Region: "Oromia / West Arsi",
        Species: "Arabica",
        Variety: "Heirloom",
        Altitude: "2100",       
        Process: "Anarobic station",
        Packaging: "60kg - jute bags",
        Harvest_period: "Nov - January",
        Type_of_harvest: "Manual",
        Drying: "Drying bed"
    },
    {
        id: "8",
        imageUrl: "/images/site1.jpg",
        siteName: "Bulga",
        fullDescription: "Located at 2,100 meters above sea level in Bulga Kebele, Nensebo Woreda, this site produces vibrant, high-elevation coffees with bold character. Bulga is known for its rich soil, cool climate, and ideal conditions for slow cherry maturation, which enhances sweetness and density. We work with local farmers cultivating heirloom varieties, some of which trace their origins to wild forest genetics unique to Ethiopia. Our specialty is the anaerobic fermentation process, where cherries are fermented in oxygen-free tanks to unlock exotic, best flavors. Bulga is part of our Sidama Nensebo network, representing a new wave of innovation in traditional coffee regions. From farm to fermentation tank, Bulga Anaerobic is a bold expression of flavor, craft, and altitude.",
        btn: "Read More",
        location: "Ethiopia / Nensebo",
        origin: "Ethiopia",
        Region: "Oromia / West Arsi",
        Species: "Arabica",
        Variety: "Heirloom",
        Altitude: "2100",       
        Process: "Anarobic station",
        Packaging: "60kg - jute bags",
        Harvest_period: "Nov - January",
        Type_of_harvest: "Manual",
        Drying: "Drying bed"
    },
    {
        id: "9",
        imageUrl: "/images/site6.jpg",
        siteName: "Mendoyu",
        fullDescription: "Perched at an impressive 2,200 meters in the highlands of Nenesbo, Mendoyu is where the rare and elegant Ethiopia coffee variety flourishes. This site benefits from cool mountain air, misty mornings, and rich, fertile soil—perfect for slow coffee cherry maturation. We specialize in the washed process, carefully controlling fermentation and drying to preserve the delicate floral and citrus notes Ethiopia coffee is known for. At Mendoyu, every cherry is selectively handpicked, ensuring only the ripest, most flavorful fruit makes it into your cup. The altitude and microclimate combine to create a cup that is complex, aromatic, and silky-smooth, with jasmine, bergamot, and stone fruit notes. Mendoyu stands as a symbol of precision and elegance, showcasing Ethiopia’s potential to produce world-class specialty coffee. Our practices are rooted in tradition, but our vision is focused on innovation, traceability, and quality at every step. This is more than a farm—it’s a curated experience for coffee lovers seeking something exceptional. Discover the unique story and flavor of Ethiopian coffee from the heights of Mendoyu.",
        btn: "Read More",
        location: "Ethiopia / Nensebo",
        origin: "Ethiopia",
        Region: "Oromia / West Arsi",
        Species: "Arabica",
        Variety: "Heirloom",
        Altitude: "2200m",       
        Process: "Washing station",
        Packaging: "60kg - jute bags",
        Harvest_period: "Nov - January",
        Type_of_harvest: "Manual",
        Drying: "Drying bed"
    },
    {
        id: "10",
        imageUrl: "/images/tade-8.jpg",
        siteName: "Bulga",
        fullDescription: "Nestled at 2,100 meters above sea level in the scenic hills of Nensebo, West Arsi, Bulga is known for its sun-dried, naturally processed coffees. Bulga coffee site dedicated to improving the quality of our coffee with the collaboration of above 50 site workers and more than 200 members of farmers It’s located 10 km from the wordal town and about 400km from Addis Ababa",
        btn: "Read More",
        location: "Ethiopia / Nensebo",
        origin: "Ethiopia",
        Region: "Oromia / West Arsi",
        Species: "Arabica",
        Variety: "Heirloom",
        Altitude: "2200m",       
        Process: "Sun dried station",
        Packaging: "60kg - jute bags",
        Harvest_period: "Nov - January",
        Type_of_harvest: "Manual",
        Drying: "Drying bed"
    },
];

export default OurSite;