import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Nunito_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import Footer from "./components/footer/page";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const opensans = Open_Sans ({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Nensebo coffee suply",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  return (
    <html lang="en">
      <body
        className={nunitoSans.className}>

        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
