import type { Metadata } from "next";
import { Montserrat, Nunito_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import Footer from "./components/footer/page";


export const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
})
export const montserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Nensebo coffee suply",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  return (
    <html lang="en">
      <body
        className={montserrat.className}>

        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
