import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Nunito, Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";

const montserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const opensans = Open_Sans ({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const nunitoSans = Nunito({
  variable: "--font-nunito-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Nensebo coffee suply",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  return (
    <html lang="en">
      <body
        className={montserrat.className}>
  
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
